return {
	"nvim-neo-tree/neo-tree.nvim",
	branch = "v3.x",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-tree/nvim-web-devicons",
		"MunifTanjim/nui.nvim",
	},
	cmd = "Neotree",
	opts = {
		close_if_last_window = true,
		popup_border_style = "rounded",
		enable_git_status = true,
		enable_diagnostics = false,
		enable_modified_markers = false,
		enable_opened_markers = true,
		open_files_do_not_replace_types = { "terminal", "trouble", "qf" },
		default_component_configs = {
			container = {
				enable_character_fade = true,
			},
			indent = {
				indent_size = 2,
				padding = 1,
				with_expanders = true,
				expander_collapsed = "",
				expander_expanded = "",
				expander_highlight = "NeoTreeExpander",
				with_indent_markers = true,
				indent_marker = "│",
				last_indent_marker = "└",
				highlight = "NeoTreeIndentMarker",
			},
			icon = {
				folder_closed = "",
				folder_open = "",
				folder_empty = "",
				default = "󰈔",
				highlight = "NeoTreeFileIcon",
			},
			modified = {
				symbol = "● ",
				highlight = "NeoTreeModified",
			},
			name = {
				trailing_slash = false,
				use_git_status_colors = true,
				highlight = "NeoTreeFileName",
			},
			git_status = {
				symbols = {
					added = "A",
					deleted = "D",
					modified = "M",
					renamed = "R",
					untracked = "?",
					ignored = "I",
					unstaged = "",
					staged = "",
					conflict = "C",
				},
				align = "right",
			},
		},
		window = {
			position = "left",
			width = 35,
			mapping_options = {
				noremap = true,
				nowait = true,
			},
			mappings = {
				["<CR>"] = "open",
				["o"] = "open",
				["<esc>"] = "cancel",
				["q"] = "close_window",
				["P"] = { "toggle_preview", config = { use_float = true, width = 60, height = 25 } },
				["l"] = "focus_preview",
				["S"] = "open_split",
				["s"] = "open_vsplit",
				["t"] = "open_tabnew",
				["C"] = "close_node",
				["z"] = "close_all_nodes",
				["Z"] = "expand_all_nodes",
				["a"] = { "add", config = { show_path = "relative" } },
				["A"] = "add_directory",
				["d"] = "delete",
				["r"] = "rename",
				["y"] = "copy_to_clipboard",
				["x"] = "cut_to_clipboard",
				["p"] = "paste_from_clipboard",
				["c"] = "copy",
				["m"] = "move",
				["R"] = "refresh",
				["?"] = "show_help",
				["<"] = "prev_source",
				[">"] = "next_source",
				["i"] = "show_file_details",
			},
		},
		filesystem = {
			filtered_items = {
				visible = false,
				hide_dotfiles = true,
				hide_gitignored = true,
				hide_hidden = true,
				never_show = { ".DS_Store", "thumbs.db" },
			},
			follow_current_file = {
				enabled = true,
				leave_dirs_open = false,
			},
			group_empty_dirs = true,
			use_libuv_file_watcher = true,
			window = {
				mappings = {
					["H"] = "toggle_hidden",
					["I"] = "toggle_gitignore",
					["<bs>"] = "navigate_up",
					["."] = "set_root",
				},
			},
		},
		buffers = {
			follow_current_file = { enabled = true },
			group_empty_dirs = true,
		},
		git_status = {
			window = {
				position = "float",
				mappings = {
					["A"] = "git_add_all",
					["gu"] = "git_unstage_file",
					["ga"] = "git_add_file",
					["gr"] = "git_revert_file",
					["gc"] = "git_commit",
					["gp"] = "git_push",
					["gg"] = "git_pull",
				},
			},
		},
		sources = { "filesystem", "buffers", "git_status" },
		source_selector = {
			winbar = true,
			statusline = false,
			sources = {
				{ source = "filesystem", display_name = " 󰉓 Files " },
				{ source = "buffers", display_name = "  Buffers " },
				{ source = "git_status", display_name = " 󰊢 Git " },
			},
		},
	},
}
